// ============================================================
//  questions.js — Banque de questions pour le Quiz d'Alignement
//  La Table Ronde (mais carrée) — Domaine du Roi Karl
//  100 questions au total : 50 par axe
//  Axe ORDRE  : Loyal (L) vs Neutre (N) vs Chaotique (C)
//  Axe MORALE : Bon   (B) vs Neutre (N) vs Mauvais   (M)
// ============================================================

const banqueQuestions = {

    // ── AXE ORDRE : Loyal vs Chaotique ──────────────────────────
    "ordre": [
        { q: "Un messager apporte un ordre de votre suzerain qui contredit vos principes. Que faites-vous ?",
          r: { L: "J'obéis sans discuter — le rang prime sur l'individu.", N: "Je cherche un compromis pour satisfaire les deux parties.", C: "Je déchire la lettre et suis mon propre chemin." }},
        { q: "Une ville est en proie au chaos. Quel est votre premier réflexe ?",
          r: { L: "Rétablir la garde et imposer un couvre-feu strict.", N: "Aider les gens au cas par cas selon l'urgence.", C: "Profiter de la confusion pour renverser les puissants corrompus." }},
        { q: "Vous trouvez un code de lois ancien et poussiéreux. Pour vous, c'est...",
          r: { L: "Une relique sacrée qui doit guider notre futur.", N: "Un document historique intéressant mais à adapter.", C: "Un tas de papier qui ne devrait plus entraver personne." }},
        { q: "Le destin vous offre une armée. Comment la dirigez-vous ?",
          r: { L: "Avec une discipline de fer et une hiérarchie absolue.", N: "Avec souplesse, en écoutant mes lieutenants.", C: "Comme une bande de frères d'armes libres de leurs actes." }},
        { q: "Un noble vous demande de trahir un ami pour respecter un contrat signé. Vous...",
          r: { L: "Respectez le contrat — une signature est sacrée.", N: "Cherchez une faille légale pour satisfaire les deux.", C: "Déchirez le contrat — l'amitié vaut plus que l'encre." }},
        { q: "Quelle est votre vision idéale d'une cité prospère ?",
          r: { L: "Des lois strictes, une garde vigilante et une hiérarchie claire.", N: "Un équilibre entre liberté individuelle et règles communes.", C: "Un endroit où chacun fait ce qu'il veut sans rendre de comptes." }},
        { q: "Un prisonnier s'échappe de votre geôle. Que faites-vous ?",
          r: { L: "Je lance immédiatement une traque organisée.", N: "J'enquête sur les raisons de son évasion avant d'agir.", C: "Je laisse faire — si la cage ne tenait pas, c'est qu'il méritait la liberté." }},
        { q: "On vous offre le poste de Grand Juge du royaume. Vous...",
          r: { L: "Acceptez avec fierté et appliquerez la loi à la lettre.", N: "Acceptez à condition de pouvoir adapter les sentences au contexte.", C: "Refusez — vous ne voulez pas être l'instrument d'un système." }},
        { q: "Face à une tradition ancestrale injuste, vous...",
          r: { L: "La respectez — elle a tenu des siècles pour une raison.", N: "En discutez avec les anciens pour trouver une réforme acceptable.", C: "La brisez publiquement pour montrer qu'elle n'a aucun pouvoir sur vous." }},
        { q: "Votre capitaine vous ordonne de vous retirer d'une bataille que vous pourriez gagner. Vous...",
          r: { L: "Obéissez immédiatement sans poser de questions.", N: "Demandez une explication avant de décider.", C: "Continuez le combat — la victoire est à portée de main." }},
        { q: "Vous rédigez votre propre code d'honneur personnel. Il contient...",
          r: { L: "Des règles précises et non-négociables pour chaque situation.", N: "Des principes généraux adaptables selon le contexte.", C: "Rien — vous ne vous liez à aucun code écrit." }},
        { q: "Un témoin clé refuse de déposer par peur des représailles. Vous...",
          r: { L: "Exigez son témoignage au nom de la loi.", N: "Négociez sa protection en échange de sa déposition.", C: "Agissez vous-même sans attendre le processus judiciaire." }},
        { q: "Vous découvrez que le roi est corrompu. Quelle est votre réaction ?",
          r: { L: "Je cherche à le renverser légalement par les institutions.", N: "Je tente de le convaincre de se réformer en privé.", C: "J'organise une révolte populaire immédiatement." }},
        { q: "On vous demande de surveiller un quartier entier par prévention. Vous...",
          r: { L: "Installez une surveillance permanente et méthodique.", N: "Surveillez discrètement les individus suspects seulement.", C: "Refusez — on ne punit pas les innocents par précaution." }},
        { q: "Quelle phrase décrit le mieux votre rapport à l'autorité ?",
          r: { L: "L'autorité légitime mérite obéissance inconditionnelle.", N: "L'autorité mérite le respect si elle est juste et raisonnable.", C: "Toute autorité est suspecte jusqu'à preuve du contraire." }},
        { q: "Un général victorieux enfreint les règles de guerre pour gagner plus vite. Vous...",
          r: { L: "Le faites traduire devant un tribunal militaire.", N: "L'avertissez sévèrement mais tenez compte de la victoire.", C: "Le célébrez — les règles de guerre sont faites par les perdants." }},
        { q: "Vous fondez votre propre ordre chevaleresque. Votre premier acte est...",
          r: { L: "Rédiger un serment et un règlement de 40 articles.", N: "Définir quelques valeurs fondamentales en accord avec mes pairs.", C: "Réunir les meilleurs guerriers sans poser aucune condition." }},
        { q: "Un citoyen enfreint une loi absurde mais inoffensive. Vous...",
          r: { L: "L'avertissez — les lois sont les lois, même imparfaites.", N: "Fermez les yeux cette fois, mais signalez la loi pour révision.", C: "Le félicitez discrètement pour son bon sens." }},
        { q: "Votre peuple veut brûler les archives royales corrompues. Vous...",
          r: { L: "Défendez les archives — détruire des lois crée l'anarchie.", N: "Trier les documents valides avant de décider.", C: "Laissez le feu purifier ce que les institutions n'ont pu nettoyer." }},
        { q: "Un proscrit condamné injustement se cache chez vous. La garde arrive. Vous...",
          r: { L: "Le livrez — la loi doit suivre son cours, même imparfaite.", N: "Gagnez du temps pour prouver son innocence avant qu'il soit pris.", C: "Le cachez et mentez à la garde sans hésiter." }},
        { q: "Selon vous, un bon dirigeant doit avant tout...",
          r: { L: "Appliquer les lois avec rigueur et impartialité.", N: "Équilibrer justice et compassion selon les circonstances.", C: "Inspirer, pas commander — la liberté crée la loyauté." }},
        { q: "On vous confie la garde d'une frontière. Votre protocole est...",
          r: { L: "Aucun passage sans documents en règle, aucune exception.", N: "Vérification rigoureuse, avec discernement pour les cas humains.", C: "Les gens passent librement — les frontières sont des inventions des puissants." }},
        { q: "Quelle est la pire chose qu'un dirigeant puisse faire ?",
          r: { L: "Agir en dehors des lois qu'il est censé défendre.", N: "Ignorer les conséquences humaines de ses décisions.", C: "Priver son peuple de liberté au nom de l'ordre." }},
        { q: "Un accord de paix vous semble injuste mais légal. Vous...",
          r: { L: "Le signez — un accord légal doit être honoré.", N: "Le signez avec des réserves et cherchez à le renégocier.", C: "Refusez de signer — votre conscience prime sur le parchemin." }},
        { q: "Votre idée d'une révolution réussie, c'est...",
          r: { L: "Un changement constitutionnel ordonné et pacifique.", N: "Une réforme progressive négociée avec toutes les parties.", C: "Un soulèvement populaire qui renverse tout d'un coup." }},
        { q: "On vous demande d'espionner un allié pour prévenir une menace. Vous...",
          r: { L: "Refusez — trahir un allié va contre tout traité.", N: "Acceptez discrètement si la menace est prouvée et grave.", C: "Espionnez sans hésiter — mieux vaut savoir que faire confiance aveuglément." }},
        { q: "Dans votre domaine, les impôts sont-ils...",
          r: { L: "Fixés par la loi et prélevés sans exception ni faveur.", N: "Adaptés selon la situation économique de chaque habitant.", C: "Remplacés par des contributions volontaires à la communauté." }},
        { q: "Un oracle prédit une catastrophe si vous enfreignez une règle sacrée. Vous...",
          r: { L: "Respectez la règle — les prophéties confirment l'ordre naturel.", N: "Cherchez une interprétation plus souple de la règle.", C: "Enfreignez la règle — le destin ne dicte rien à un homme libre." }},
        { q: "Vous héritez d'un titre nobiliaire. Votre première décision est...",
          r: { L: "Étudier tous les textes de loi qui régissent votre nouveau rôle.", N: "Rencontrer le peuple et vos pairs pour comprendre les besoins.", C: "Ignorer les protocoles et gouverner selon votre instinct." }},
        { q: "Quel est le fondement d'une société juste ?",
          r: { L: "Des lois claires appliquées équitablement pour tous.", N: "Un dialogue permanent entre dirigeants et dirigés.", C: "La liberté absolue tempérée par la responsabilité individuelle." }},
        { q: "Un traître repenti demande à reintégrer vos rangs. Vous...",
          r: { L: "Refusez — la trahison est une faute impardonnable selon le code.", N: "Accordez une période de probation sous surveillance.", C: "Accueillez-le — tout homme mérite de repartir de zéro." }},
        { q: "Vous devez choisir entre vitesse et procédure lors d'une crise. Vous...",
          r: { L: "Suivez la procédure — elle existe pour les moments de crise.", N: "Adaptez la procédure pour agir vite sans perdre le contrôle.", C: "Agissez immédiatement — les procédures paralysent quand il faut bouger." }},
        { q: "On vous propose de rejoindre une société secrète influente. Vous...",
          r: { L: "Refusez — tout pouvoir doit être public et accountable.", N: "Étudiez leurs intentions avant de décider.", C: "Acceptez avec enthousiasme — l'ombre a ses avantages." }},
        { q: "Votre conception de la liberté, c'est...",
          r: { L: "La liberté dans le cadre des lois — la vraie liberté est ordonnée.", N: "Un équilibre entre droits individuels et bien collectif.", C: "Faire ce qu'on veut sans rendre de comptes à personne." }},
        { q: "Un détenu purge une peine injustement longue. Vous...",
          r: { L: "Soumettez une requête en grâce par les voies légales.", N: "Intervenez personnellement auprès du juge.", C: "Organisez son évasion cette nuit même." }},
        { q: "Votre lieutenant prend une initiative non-autorisée qui sauve des vies. Vous...",
          r: { L: "Le sanctionnez tout de même — la discipline prime.", N: "Le félicitez en privé mais clarifiez les règles pour l'avenir.", C: "Le promouvez — l'initiative courageuse mérite récompense." }},
        { q: "Face à une loi que vous trouvez absurde, vous...",
          r: { L: "L'appliquez en attendant de la changer par les voies officielles.", N: "L'appliquez avec discernement selon les cas.", C: "La ignorez ouvertement pour montrer qu'elle n'a aucun sens." }},
        { q: "Comment punissez-vous un officier qui a enfreint un ordre pour sauver sa garnison ?",
          r: { L: "Punition symbolique obligatoire — l'ordre prime même en cas de succès.", N: "Aucune punition si le résultat était le bon, mais un avertissement.", C: "Médaille et promotion — il a fait ce qu'il fallait." }},
        { q: "Votre vision des frontières entre nations est...",
          r: { L: "Sacrées — elles définissent la souveraineté et l'ordre mondial.", N: "Utiles mais révisables par traités mutuels.", C: "Des lignes tracées sur le sable par des vieillards avides de pouvoir." }},
        { q: "Un enfant vole du pain. Selon vous...",
          r: { L: "La loi s'applique à tous — il faut un avertissement formel.", N: "On cherche pourquoi il avait faim et on règle le problème.", C: "On le nourrit et on se demande pourquoi la société l'a laissé affamé." }},
        { q: "Vous organisez un tournoi. Votre règlement est...",
          r: { L: "Strict, écrit à l'avance, sans exception ni accommodement.", N: "Clair mais adaptable pour les cas imprévus.", C: "Minimal — que les meilleurs se distinguent naturellement." }},
        { q: "Un espion ennemi est capturé. La procédure légale est longue. Vous...",
          r: { L: "Respectez la procédure — même les ennemis ont droit à un procès.", N: "Accélérez le processus par des voies légales d'urgence.", C: "L'interrogez vous-même et décidez de son sort sur le champ." }},
        { q: "Selon vous, qu'est-ce qui légitime le pouvoir d'un roi ?",
          r: { L: "Sa conformité aux lois et traditions établies.", N: "Sa capacité à servir le bien de son peuple.", C: "Rien — le pouvoir se prend, pas se légitime." }},
        { q: "Vous trouvez une faille dans une loi qui vous avantagerait. Vous...",
          r: { L: "La signalez aux autorités pour la corriger.", N: "L'utilisez une fois si c'est juste, puis la signalez.", C: "L'exploitez tant que personne ne la voit — les règles profitent à qui sait les lire." }},
        { q: "Un artisan fabrique un produit dangereux mais légal. Vous...",
          r: { L: "Laissez faire — la loi autorise, vous n'avez pas à intervenir.", N: "Discutez avec lui des risques pour qu'il ajuste sa pratique.", C: "Détruisez les stocks vous-même — la loi a tort." }},
        { q: "Votre rapport aux serments est...",
          r: { L: "Sacré — un serment brisé est une mort morale.", N: "Sérieux — sauf circonstances exceptionnelles qui changent tout.", C: "Symbolique — les mots prononcés ne peuvent enchaîner que ceux qui le veulent." }},
        { q: "On vous offre de gouverner une province isolée sans contrôle extérieur. Vous...",
          r: { L: "Gouvernez selon les lois du royaume, même sans supervision.", N: "Adaptez les lois aux réalités locales avec sagesse.", C: "Créez une communauté entièrement nouvelle selon vos principes." }},
        { q: "Quelle est votre réaction face à une mutinerie dans vos rangs ?",
          r: { L: "Répression ferme et procès des meneurs — l'ordre doit être rétabli.", N: "Dialogue avec les mutins pour comprendre et résoudre.", C: "Écoute des griefs — si la mutinerie a lieu, j'ai peut-être failli." }},
        { q: "Votre palais idéal ressemble à...",
          r: { L: "Une forteresse ordonnée avec protocoles et gardes à chaque étage.", N: "Une demeure accueillante avec quelques règles de bon sens.", C: "Une grande maison ouverte à tous, sans gardes ni protocoles." }},
        { q: "Quelle phrase résume le mieux votre philosophie politique ?",
          r: { L: "Sans loi, pas de liberté — seulement la tyrannie du plus fort.", N: "Une bonne gouvernance équilibre règles et humanité.", C: "Les meilleures lois sont celles que chaque homme s'impose à lui-même." }}
    ],

    // ── AXE MORALE : Bon vs Mauvais ─────────────────────────────
    "morale": [
        { q: "Un villageois est accusé de vol pour nourrir sa famille. La sentence est la main coupée.",
          r: { B: "Je paie sa dette pour qu'il soit libéré.", N: "Je demande une remise de peine en échange de travaux.", M: "La loi est la loi — je laisse la sentence s'exécuter." }},
        { q: "Vous découvrez une fontaine de jouvence qui ne peut soigner qu'une seule personne.",
          r: { B: "Je l'offre au plus vieux sage du royaume.", N: "Je la vends au plus offrant pour financer mon équipement.", M: "Je bois l'eau moi-même pour devenir immortel." }},
        { q: "Un dragon mourant vous supplie de protéger son dernier œuf.",
          r: { B: "Je jure de le protéger au péril de ma vie.", N: "Je le confie à un monastère en échange d'une faveur.", M: "Je brise l'œuf pour récupérer ses composants magiques précieux." }},
        { q: "Face à un ennemi désarmé qui demande grâce, vous...",
          r: { B: "Je l'épargne et lui offre une chance de rédemption.", N: "Je l'emprisonne pour qu'il ne nuise plus.", M: "Je l'achève pour être sûr qu'il ne revienne jamais." }},
        { q: "Un sorcier vous propose un sort puissant en échange de dix ans de vie d'un inconnu.",
          r: { B: "Je refuse catégoriquement — personne ne mérite ce sacrifice.", N: "Je refuse mais cherche un autre marché avec le sorcier.", M: "J'accepte — un inconnu pour un grand pouvoir, c'est raisonnable." }},
        { q: "Vous avez la possibilité d'enrichir votre village en empoisonnant la source d'eau d'un village rival.",
          r: { B: "Jamais — je trouverai une autre voie pour enrichir les miens.", N: "Je cherche une façon de les affaiblir sans mettre des vies en danger.", M: "Je le fais — la survie des miens prime sur tout." }},
        { q: "Un mendiant vous tend la main devant la taverne. Vous...",
          r: { B: "Lui donnez vos dernières pièces et l'invitez à dîner.", N: "Lui donnez une pièce — c'est déjà quelque chose.", M: "Passez votre chemin — la charité entretient la faiblesse." }},
        { q: "Vous pouvez sauver 10 personnes inconnues ou une personne que vous aimez. Vous...",
          r: { B: "Sauvez les 10 inconnus — le bien du plus grand nombre prime.", N: "Cherchez désespérément un moyen de sauver tout le monde.", M: "Sauvez la personne que vous aimez sans hésiter." }},
        { q: "Un négociant vous vend sciemment une monture malade. Vous le découvrez après. Vous...",
          r: { B: "Lui pardonnez après avoir exigé réparation pour la monture.", N: "Réclamez un remboursement complet et le signalez aux autorités.", M: "Revenez cette nuit vider sa caisse — il l'a bien mérité." }},
        { q: "Vous trouvez un orphelin sur la route en plein hiver. Vous...",
          r: { B: "L'emmenez avec vous et subvenez à ses besoins.", N: "L'amenez au prochain village avec une pièce pour son gîte.", M: "Continuez votre route — le monde est dur pour tout le monde." }},
        { q: "Un ami vous demande de mentir pour le sortir d'un mauvais pas. Vous...",
          r: { B: "Refusez le mensonge mais l'aidez à trouver une solution honnête.", N: "Mentez une fois si les conséquences pour autrui sont mineures.", M: "Mentez sans hésiter — la loyauté envers les siens avant tout." }},
        { q: "Vous découvrez un secret compromettant sur un rival. Vous...",
          r: { B: "Le gardez pour vous — utiliser ce secret serait indigne.", N: "Le conservez comme assurance mais ne l'utilisez pas activement.", M: "L'utilisez immédiatement pour éliminer la concurrence." }},
        { q: "Une guérisseuse peut soigner tous les enfants malades du village ou un seigneur puissant. Vous décidez...",
          r: { B: "Les enfants, sans hésitation — le seigneur peut attendre.", N: "Le seigneur d'abord s'il finance les soins des enfants ensuite.", M: "Le seigneur — son influence nous protégera à long terme." }},
        { q: "Votre victoire passe par la destruction d'un village neutre. Vous...",
          r: { B: "Refusez — aucune victoire ne justifie d'innocents massacrés.", N: "Cherchez une stratégie alternative même plus coûteuse.", M: "Donnez l'ordre — la guerre a ses règles cruelles." }},
        { q: "Un espion capturé possède des informations vitales. La torture est proposée. Vous...",
          r: { B: "Refusez fermement — il existe des méthodes plus humaines.", N: "Autorisez une pression psychologique mais pas physique.", M: "Autorisez tout — les informations sauvent plus de vies qu'elles n'en détruisent." }},
        { q: "Vous pouvez rester anonyme après avoir fait quelque chose de bien. Vous...",
          r: { B: "Restez dans l'ombre — le bien n'a pas besoin de témoin.", N: "Restez discret mais ne niez pas si quelqu'un vous retrouve.", M: "Revendiquez publiquement pour en tirer profit." }},
        { q: "Un mage offre de maudire votre ennemi en échange de votre première victoire militaire. Vous...",
          r: { B: "Refusez — la magie noire ne m'appartient pas.", N: "Réfléchissez longuement selon la gravité de la menace.", M: "Acceptez — une malédiction économise des batailles." }},
        { q: "Vous héritez d'une fortune bâtie sur l'esclavage. Vous...",
          r: { B: "La redistribuez intégralement aux descendants des victimes.", N: "En donnez une partie significative et bâtissez quelque chose de juste.", M: "La gardez — les erreurs du passé ne sont pas les vôtres." }},
        { q: "Un enfant vous offre sa seule pièce d'or pour que vous le vengez. Vous...",
          r: { B: "Refusez l'argent mais l'aidez quand même.", N: "Acceptez la mission mais lui rendrez l'argent à la fin.", M: "Prenez la pièce et évaluez si la mission vous profite vraiment." }},
        { q: "Une épidémie touche une région pauvre et une région riche. Vous avez un seul remède. Vous...",
          r: { B: "L'envoyez dans la région la plus touchée, peu importe le rang.", N: "Divisez le remède pour aider les deux régions partiellement.", M: "L'envoyez là où vous avez le plus à gagner politiquement." }},
        { q: "Votre victoire dépend d'un allié que vous savez innocent d'une accusation. Vous...",
          r: { B: "Prouvez son innocence même si ça compromet votre campagne.", N: "Travaillez en parallèle pour le disculper discrètement.", M: "Laissez l'accusation courir jusqu'à la victoire — le temps arrangera tout." }},
        { q: "Vous pouvez gagner une guerre en ruinant l'économie ennemie, affamant civils compris. Vous...",
          r: { B: "Refusez — on ne gagne pas une guerre sur des cadavres d'enfants.", N: "Cherchez une stratégie économique qui épargne les civils.", M: "Procédez — une faim temporaire vaut mieux qu'une guerre éternelle." }},
        { q: "Un condamné à mort vous révèle où se cache un dangereux criminel. En échange il demande la liberté. Vous...",
          r: { B: "Promettez et tenez parole, puis travaillez à sa réhabilitation.", N: "Promettez la liberté après confirmation des infos.", M: "Prenez l'information et laissez la sentence s'accomplir." }},
        { q: "Vous pouvez sauver votre honneur en sacrifiant la réputation d'un innocent. Vous...",
          r: { B: "Jamais — mon honneur n'a de valeur que s'il est réel.", N: "Cherchez une issue qui ne nuise à personne.", M: "Sacrifiez l'innocent — la survie de ma réputation est en jeu." }},
        { q: "Un vieil ennemi est tombé dans la misère. Vous le croisez par hasard. Vous...",
          r: { B: "Lui offrez de l'aide sans conditions — les vieilles rancœurs s'effacent.", N: "Passez votre chemin sans l'aider ni lui nuire.", M: "Profitez de l'occasion pour achever sa ruine." }},
        { q: "Une rumeur fausse sur vous se répand. La corriger nuirait à un ami. Vous...",
          r: { B: "Corrigez la rumeur quand même — la vérité vaut ce sacrifice.", N: "Parlez en privé à votre ami pour trouver une solution ensemble.", M: "Laissez courir la rumeur — si ça vous arrange, pourquoi pas." }},
        { q: "On vous offre une récompense pour avoir accompli votre devoir. Vous...",
          r: { B: "Refusez — le devoir ne se monnaie pas.", N: "Acceptez si la récompense est raisonnable et méritée.", M: "Négociez pour obtenir le maximum avant de conclure." }},
        { q: "Un sorcier peut vous rendre invincible en échange des souvenirs heureux d'un enfant. Vous...",
          r: { B: "Refusez avec indignation — jamais au détriment d'un enfant.", N: "Cherchez une alternative moins cruelle avec le sorcier.", M: "Acceptez — un enfant oubliera, vous avez une mission à accomplir." }},
        { q: "Vous pouvez dénoncer un ami pour un crime mineur qu'il a commis. Vous...",
          r: { B: "L'encouragez à se dénoncer lui-même et l'accompagnez.", N: "Négociez avec lui pour qu'il répare le tort sans se dénoncer.", M: "Utilisez cette information comme levier si vous en avez besoin un jour." }},
        { q: "Un ennemi blessé demande de l'eau sur le champ de bataille. Vous...",
          r: { B: "Lui tendez votre gourde sans hésiter.", N: "Lui donnez de l'eau mais restez sur vos gardes.", M: "Passez votre chemin — l'ennemi reste l'ennemi." }},
        { q: "Une sorcière peut sauver votre village en sacrifiant un criminel condamné. Vous...",
          r: { B: "Refusez — même un criminel a droit à sa vie.", N: "Cherchez une alternative avant d'accepter.", M: "Acceptez sans hésiter — il méritait pire de toute façon." }},
        { q: "Vous surprenez un serviteur qui vole de la nourriture pour sa famille affamée. Vous...",
          r: { B: "Ne dites rien et augmentez discrètement son salaire.", N: "Parlez-lui en privé et trouvez une solution juste.", M: "Le renvoyez immédiatement — le vol reste le vol." }},
        { q: "On vous propose de tester une arme nouvelle sur des condamnés à mort. Vous...",
          r: { B: "Refusez catégoriquement — personne n'est un cobaye.", N: "Refusez mais proposez des tests sur des animaux ou des cibles inanimées.", M: "Acceptez — ils sont condamnés de toute façon, autant que ça serve." }},
        { q: "Votre victoire finale est à portée mais votre ennemi vous révèle qu'il a une famille. Vous...",
          r: { B: "Offrez la paix — une famille change tout à l'équation.", N: "Concluez la paix si les conditions sont acceptables.", M: "Continuez — la sentimentalité n'a pas sa place sur un champ de bataille." }},
        { q: "Vous pouvez récupérer une relique sacrée en pillant un temple ennemi. Vous...",
          r: { B: "Négociez son rachat — les lieux de culte sont sacrés.", N: "La prenez discrètement en laissant une compensation.", M: "La prenez de force — la victoire légitime les trophées." }},
        { q: "Un mendiant affirme être un ancien roi déchu. Vous...",
          r: { B: "L'aidez de toute façon — sa parole importe peu, sa détresse oui.", N: "Vérifiez son histoire avant de décider quoi faire.", M: "Passez — si c'est vrai, il a eu sa chance de régner." }},
        { q: "Un alchimiste peut doubler vos récoltes en polluant une rivière en aval. Vous...",
          r: { B: "Refusez — les gens en aval ont autant droit à l'eau pure.", N: "Cherchez avec l'alchimiste une méthode moins polluante.", M: "Acceptez — votre peuple passe avant les inconnus en aval." }},
        { q: "Vous gagnez une bataille grâce à une ruse qui humilie publiquement l'ennemi. Vous...",
          r: { B: "Offrez à l'ennemi une sortie digne après la victoire.", N: "Profitez de la victoire sans en rajouter.", M: "Exploitez l'humiliation au maximum pour briser leur moral définitivement." }},
        { q: "On vous demande de témoigner contre un ami dont vous savez qu'il est coupable. Vous...",
          r: { B: "Témoignez honnêtement — la vérité lui rendra service à long terme.", N: "Témoignez avec nuance pour atténuer sa peine.", M: "Refusez de témoigner — la loyauté prime sur la justice." }},
        { q: "Une prophétie dit que vous pouvez sauver le monde en sacrifiant votre propre bonheur. Vous...",
          r: { B: "Acceptez sans hésiter — le monde vaut mon bonheur.", N: "Cherchez si la prophétie a une interprétation moins radicale.", M: "Cherchez quelqu'un d'autre pour faire ce sacrifice." }},
        { q: "Vous découvrez que votre mentor bien-aimé a commis des crimes dans sa jeunesse. Vous...",
          r: { B: "L'encouragez à se confesser et l'aidez à réparer ses torts.", N: "Lui en parlez en privé et laissez-le choisir sa voie.", M: "Gardez cette information pour vous — ou pour plus tard." }},
        { q: "Un enfant pauvre a du talent mais pas de ressources. Vous...",
          r: { B: "Financez sa formation vous-même et sans condition.", N: "L'aidez à trouver un mécène ou une bourse.", M: "C'est à lui de trouver comment s'en sortir — le talent ne suffit pas." }},
        { q: "Vous pouvez trahir un secret d'État pour sauver des vies innocentes. Vous...",
          r: { B: "Révélez le secret — des vies valent plus que des secrets politiques.", N: "Cherchez une façon de sauver ces vies sans révéler le secret.", M: "Gardez le secret — votre position importe plus que ces vies." }},
        { q: "Un artisan produit des œuvres magnifiques mais exploite ses apprentis. Vous...",
          r: { B: "Dénoncez ses pratiques même si ses œuvres vous manqueront.", N: "L'avertissez en privé et lui donnez une chance de changer.", M: "Continuez à acheter ses œuvres — ce qui se passe chez lui ne vous regarde pas." }},
        { q: "Vous pouvez choisir entre une victoire glorieuse avec des pertes ou une victoire humble sans victimes. Vous...",
          r: { B: "La victoire humble sans victimes, sans même hésiter.", N: "Évaluez les deux options selon le contexte stratégique.", M: "La victoire glorieuse — les grandes choses demandent de grands sacrifices." }},
        { q: "Un noble vous offre une fortune pour fermer les yeux sur ses abus envers ses serfs. Vous...",
          r: { B: "Refusez et dénoncez ses abus immédiatement.", N: "Refusez l'argent et l'avertissez sévèrement.", M: "Prenez l'argent — les serfs ont toujours été mal traités de toute façon." }},
        { q: "Quelle est selon vous la plus grande vertu ?",
          r: { B: "La compassion — souffrir avec autrui et agir pour le soulager.", N: "La sagesse — peser chaque acte pour le plus grand bien.", M: "La force — seuls les forts peuvent vraiment protéger les leurs." }},
        { q: "Un paysan vous offre sa seule vache pour payer votre protection. Vous...",
          r: { B: "Refusez la vache et le protégez gratuitement.", N: "Acceptez la moitié de ce qu'il propose.", M: "Prenez la vache — un service mérite compensation." }},
        { q: "On vous propose d'assassiner un tyran en échange de paix pour votre peuple. Vous...",
          r: { B: "Cherchez une autre voie — tuer est toujours le dernier recours.", N: "Pesez longuement les conséquences avant de décider.", M: "Acceptez sans états d'âme — un tyran de moins, c'est toujours mieux." }},
        { q: "Vous pouvez sauver un village en brûlant la forêt sacrée qui le protégeait depuis des siècles. Vous...",
          r: { B: "Cherchez une alternative coûteuse mais respectueuse de l'héritage.", N: "Brûlez la forêt en promettant de la replanter sur plusieurs générations.", M: "Brûlez sans hésiter — les vivants d'aujourd'hui comptent plus que les symboles." }}
    ]
};
