// ============================================================
//  questions.js — Banque de questions pour le Quiz d'Alignement
//  La Table Ronde (mais carrée) — Domaine du Roi Karl
//  200 questions au total : 100 par axe
//  Axe ORDRE  : Loyal (L) vs Neutre (N) vs Chaotique (C)
//  Axe MORALE : Bon   (B) vs Neutre (N) vs Mauvais   (M)
// ============================================================

const banqueQuestions = {

    // ── AXE ORDRE : Loyal vs Chaotique ──────────────────────────
    "ordre": [
        { q: "Un messager apporte un ordre de votre suzerain qui contredit vos principes. Que faites-vous ?",
          r: { L: "J'obéis sans discuter — le rang prime sur l'individu.", N: "Je cherche un compromis pour satisfaire les deux parties.", C: "Je déchire la lettre et suis mon propre chemin." }},
        { q: "Une ville est en proie au chaos. Quel est votre premier réflexe ?",
          r: { L: "Rétablir la garde et imposer un couvre-feu strict.", N: "Aider les gens au cas par cas selon l'urgence.", C: "Profiter de la confusion pour renverser les puissants corrompus." }},
        { q: "Vous trouvez un code de lois ancien et poussiéreux. Pour vous, c'est...",
          r: { L: "Une relique sacrée qui doit guider notre futur.", N: "Un document historique intéressant mais à adapter.", C: "Un tas de papier qui ne devrait plus entraver personne." }},
        { q: "Le destin vous offre une armée. Comment la dirigez-vous ?",
          r: { L: "Avec une discipline de fer et une hiérarchie absolue.", N: "Avec souplesse, en écoutant mes lieutenants.", C: "Comme une bande de frères d'armes libres de leurs actes." }},
        { q: "Un noble vous demande de trahir un ami pour respecter un contrat signé. Vous...",
          r: { L: "Respectez le contrat — une signature est sacrée.", N: "Cherchez une faille légale pour satisfaire les deux.", C: "Déchirez le contrat — l'amitié vaut plus que l'encre." }},
        { q: "Quelle est votre vision idéale d'une cité prospère ?",
          r: { L: "Des lois strictes, une garde vigilante et une hiérarchie claire.", N: "Un équilibre entre liberté individuelle et règles communes.", C: "Un endroit où chacun fait ce qu'il veut sans rendre de comptes." }},
        { q: "Un prisonnier s'échappe de votre geôle. Que faites-vous ?",
          r: { L: "Je lance immédiatement une traque organisée.", N: "J'enquête sur les raisons de son évasion avant d'agir.", C: "Je laisse faire — si la cage ne tenait pas, c'est qu'il méritait la liberté." }},
        { q: "On vous offre le poste de Grand Juge du royaume. Vous...",
          r: { L: "Acceptez avec fierté et appliquerez la loi à la lettre.", N: "Acceptez à condition de pouvoir adapter les sentences au contexte.", C: "Refusez — vous ne voulez pas être l'instrument d'un système." }},
        { q: "Face à une tradition ancestrale injuste, vous...",
          r: { L: "La respectez — elle a tenu des siècles pour une raison.", N: "En discutez avec les anciens pour trouver une réforme acceptable.", C: "La brisez publiquement pour montrer qu'elle n'a aucun pouvoir sur vous." }},
        { q: "Votre capitaine vous ordonne de vous retirer d'une bataille que vous pourriez gagner. Vous...",
          r: { L: "Obéissez immédiatement sans poser de questions.", N: "Demandez une explication avant de décider.", C: "Continuez le combat — la victoire est à portée de main." }},
        { q: "Vous rédigez votre propre code d'honneur personnel. Il contient...",
          r: { L: "Des règles précises et non-négociables pour chaque situation.", N: "Des principes généraux adaptables selon le contexte.", C: "Rien — vous ne vous liez à aucun code écrit." }},
        { q: "Un témoin clé refuse de déposer par peur des représailles. Vous...",
          r: { L: "Exigez son témoignage au nom de la loi.", N: "Négociez sa protection en échange de sa déposition.", C: "Agissez vous-même sans attendre le processus judiciaire." }},
        { q: "Vous découvrez que le roi est corrompu. Quelle est votre réaction ?",
          r: { L: "Je cherche à le renverser légalement par les institutions.", N: "Je tente de le convaincre de se réformer en privé.", C: "J'organise une révolte populaire immédiatement." }},
        { q: "On vous demande de surveiller un quartier entier par prévention. Vous...",
          r: { L: "Installez une surveillance permanente et méthodique.", N: "Surveillez discrètement les individus suspects seulement.", C: "Refusez — on ne punit pas les innocents par précaution." }},
        { q: "Quelle phrase décrit le mieux votre rapport à l'autorité ?",
          r: { L: "L'autorité légitime mérite obéissance inconditionnelle.", N: "L'autorité mérite le respect si elle est juste et raisonnable.", C: "Toute autorité est suspecte jusqu'à preuve du contraire." }},
        { q: "Un général victorieux enfreint les règles de guerre pour gagner plus vite. Vous...",
          r: { L: "Le faites traduire devant un tribunal militaire.", N: "L'avertissez sévèrement mais tenez compte de la victoire.", C: "Le célébrez — les règles de guerre sont faites par les perdants." }},
        { q: "Vous fondez votre propre ordre chevaleresque. Votre premier acte est...",
          r: { L: "Rédiger un serment et un règlement de 40 articles.", N: "Définir quelques valeurs fondamentales en accord avec mes pairs.", C: "Réunir les meilleurs guerriers sans poser aucune condition." }},
        { q: "Un citoyen enfreint une loi absurde mais inoffensive. Vous...",
          r: { L: "L'avertissez — les lois sont les lois, même imparfaites.", N: "Fermez les yeux cette fois, mais signalez la loi pour révision.", C: "Le félicitez discrètement pour son bon sens." }},
        { q: "Votre peuple veut brûler les archives royales corrompues. Vous...",
          r: { L: "Défendez les archives — détruire des lois crée l'anarchie.", N: "Trier les documents valides avant de décider.", C: "Laissez le feu purifier ce que les institutions n'ont pu nettoyer." }},
        { q: "Un proscrit condamné injustement se cache chez vous. La garde arrive. Vous...",
          r: { L: "Le livrez — la loi doit suivre son cours, même imparfaite.", N: "Gagnez du temps pour prouver son innocence avant qu'il soit pris.", C: "Le cachez et mentez à la garde sans hésiter." }},
        { q: "Selon vous, un bon dirigeant doit avant tout...",
          r: { L: "Appliquer les lois avec rigueur et impartialité.", N: "Équilibrer justice et compassion selon les circonstances.", C: "Inspirer, pas commander — la liberté crée la loyauté." }},
        { q: "On vous confie la garde d'une frontière. Votre protocole est...",
          r: { L: "Aucun passage sans documents en règle, aucune exception.", N: "Vérification rigoureuse, avec discernement pour les cas humains.", C: "Les gens passent librement — les frontières sont des inventions des puissants." }},
        { q: "Quelle est la pire chose qu'un dirigeant puisse faire ?",
          r: { L: "Agir en dehors des lois qu'il est censé défendre.", N: "Ignorer les conséquences humaines de ses décisions.", C: "Priver son peuple de liberté au nom de l'ordre." }},
        { q: "Un accord de paix vous semble injuste mais légal. Vous...",
          r: { L: "Le signez — un accord légal doit être honoré.", N: "Le signez avec des réserves et cherchez à le renégocier.", C: "Refusez de signer — votre conscience prime sur le parchemin." }},
        { q: "Votre idée d'une révolution réussie, c'est...",
          r: { L: "Un changement constitutionnel ordonné et pacifique.", N: "Une réforme progressive négociée avec toutes les parties.", C: "Un soulèvement populaire qui renverse tout d'un coup." }},
        { q: "On vous demande d'espionner un allié pour prévenir une menace. Vous...",
          r: { L: "Refusez — trahir un allié va contre tout traité.", N: "Acceptez discrètement si la menace est prouvée et grave.", C: "Espionnez sans hésiter — mieux vaut savoir que faire confiance aveuglément." }},
        { q: "Dans votre domaine, les impôts sont-ils...",
          r: { L: "Fixés par la loi et prélevés sans exception ni faveur.", N: "Adaptés selon la situation économique de chaque habitant.", C: "Remplacés par des contributions volontaires à la communauté." }},
        { q: "Un oracle prédit une catastrophe si vous enfreignez une règle sacrée. Vous...",
          r: { L: "Respectez la règle — les prophéties confirment l'ordre naturel.", N: "Cherchez une interprétation plus souple de la règle.", C: "Enfreignez la règle — le destin ne dicte rien à un homme libre." }},
        { q: "Vous héritez d'un titre nobiliaire. Votre première décision est...",
          r: { L: "Étudier tous les textes de loi qui régissent votre nouveau rôle.", N: "Rencontrer le peuple et vos pairs pour comprendre les besoins.", C: "Ignorer les protocoles et gouverner selon votre instinct." }},
        { q: "Quel est le fondement d'une société juste ?",
          r: { L: "Des lois claires appliquées équitablement pour tous.", N: "Un dialogue permanent entre dirigeants et dirigés.", C: "La liberté absolue tempérée par la responsabilité individuelle." }},
        { q: "Un traître repenti demande à reintégrer vos rangs. Vous...",
          r: { L: "Refusez — la trahison est une faute impardonnable selon le code.", N: "Accordez une période de probation sous surveillance.", C: "Accueillez-le — tout homme mérite de repartir de zéro." }},
        { q: "Vous devez choisir entre vitesse et procédure lors d'une crise. Vous...",
          r: { L: "Suivez la procédure — elle existe pour les moments de crise.", N: "Adaptez la procédure pour agir vite sans perdre le contrôle.", C: "Agissez immédiatement — les procédures paralysent quand il faut bouger." }},
        { q: "On vous propose de rejoindre une société secrète influente. Vous...",
          r: { L: "Refusez — tout pouvoir doit être public et accountable.", N: "Étudiez leurs intentions avant de décider.", C: "Acceptez avec enthousiasme — l'ombre a ses avantages." }},
        { q: "Votre conception de la liberté, c'est...",
          r: { L: "La liberté dans le cadre des lois — la vraie liberté est ordonnée.", N: "Un équilibre entre droits individuels et bien collectif.", C: "Faire ce qu'on veut sans rendre de comptes à personne." }},
        { q: "Un détenu purge une peine injustement longue. Vous...",
          r: { L: "Soumettez une requête en grâce par les voies légales.", N: "Intervenez personnellement auprès du juge.", C: "Organisez son évasion cette nuit même." }},
        { q: "Votre lieutenant prend une initiative non-autorisée qui sauve des vies. Vous...",
          r: { L: "Le sanctionnez tout de même — la discipline prime.", N: "Le félicitez en privé mais clarifiez les règles pour l'avenir.", C: "Le promouvez — l'initiative courageuse mérite récompense." }},
        { q: "Face à une loi que vous trouvez absurde, vous...",
          r: { L: "L'appliquez en attendant de la changer par les voies officielles.", N: "L'appliquez avec discernement selon les cas.", C: "La ignorez ouvertement pour montrer qu'elle n'a aucun sens." }},
        { q: "Comment punissez-vous un officier qui a enfreint un ordre pour sauver sa garnison ?",
          r: { L: "Punition symbolique obligatoire — l'ordre prime même en cas de succès.", N: "Aucune punition si le résultat était le bon, mais un avertissement.", C: "Médaille et promotion — il a fait ce qu'il fallait." }},
        { q: "Votre vision des frontières entre nations est...",
          r: { L: "Sacrées — elles définissent la souveraineté et l'ordre mondial.", N: "Utiles mais révisables par traités mutuels.", C: "Des lignes tracées sur le sable par des vieillards avides de pouvoir." }},
        { q: "Un enfant vole du pain. Selon vous...",
          r: { L: "La loi s'applique à tous — il faut un avertissement formel.", N: "On cherche pourquoi il avait faim et on règle le problème.", C: "On le nourrit et on se demande pourquoi la société l'a laissé affamé." }},
        { q: "Vous organisez un tournoi. Votre règlement est...",
          r: { L: "Strict, écrit à l'avance, sans exception ni accommodement.", N: "Clair mais adaptable pour les cas imprévus.", C: "Minimal — que les meilleurs se distinguent naturellement." }},
        { q: "Un espion ennemi est capturé. La procédure légale est longue. Vous...",
          r: { L: "Respectez la procédure — même les ennemis ont droit à un procès.", N: "Accélérez le processus par des voies légales d'urgence.", C: "L'interrogez vous-même et décidez de son sort sur le champ." }},
        { q: "Selon vous, qu'est-ce qui légitime le pouvoir d'un roi ?",
          r: { L: "Sa conformité aux lois et traditions établies.", N: "Sa capacité à servir le bien de son peuple.", C: "Rien — le pouvoir se prend, pas se légitime." }},
        { q: "Vous trouvez une faille dans une loi qui vous avantagerait. Vous...",
          r: { L: "La signalez aux autorités pour la corriger.", N: "L'utilisez une fois si c'est juste, puis la signalez.", C: "L'exploitez tant que personne ne la voit — les règles profitent à qui sait les lire." }},
        { q: "Un artisan fabrique un produit dangereux mais légal. Vous...",
          r: { L: "Laissez faire — la loi autorise, vous n'avez pas à intervenir.", N: "Discutez avec lui des risques pour qu'il ajuste sa pratique.", C: "Détruisez les stocks vous-même — la loi a tort." }},
        { q: "Votre rapport aux serments est...",
          r: { L: "Sacré — un serment brisé est une mort morale.", N: "Sérieux — sauf circonstances exceptionnelles qui changent tout.", C: "Symbolique — les mots prononcés ne peuvent enchaîner que ceux qui le veulent." }},
        { q: "On vous offre de gouverner une province isolée sans contrôle extérieur. Vous...",
          r: { L: "Gouvernez selon les lois du royaume, même sans supervision.", N: "Adaptez les lois aux réalités locales avec sagesse.", C: "Créez une communauté entièrement nouvelle selon vos principes." }},
        { q: "Quelle est votre réaction face à une mutinerie dans vos rangs ?",
          r: { L: "Répression ferme et procès des meneurs — l'ordre doit être rétabli.", N: "Dialogue avec les mutins pour comprendre et résoudre.", C: "Écoute des griefs — si la mutinerie a lieu, j'ai peut-être failli." }},
        { q: "Votre palais idéal ressemble à...",
          r: { L: "Une forteresse ordonnée avec protocoles et gardes à chaque étage.", N: "Une demeure accueillante avec quelques règles de bon sens.", C: "Une grande maison ouverte à tous, sans gardes ni protocoles." }},
        { q: "Quelle phrase résume le mieux votre philosophie politique ?",
          r: { L: "Sans loi, pas de liberté — seulement la tyrannie du plus fort.", N: "Une bonne gouvernance équilibre règles et humanité.", C: "Les meilleures lois sont celles que chaque homme s'impose à lui-même." }},
        { q: "Le Baron impose une taxe illégale pour réparer les remparts. Que faites-vous ?", r: { L: "Je paie, la sécurité de la cité prime sur les détails légaux.", N: "Je paie mais je signe une pétition de protestation.", C: "Je refuse de payer une taxe qui ne respecte pas la charte." }},
        { q: "Vous trouvez un manuel de combat interdit par l'Inquisition.", r: { L: "Je le remets immédiatement aux autorités pour qu'il soit brûlé.", N: "Je le cache dans une bibliothèque pour l'étude historique.", C: "Je l'apprends en secret pour obtenir un avantage unique." }},
        { q: "Un ami proche a déserté l'armée pendant une bataille mineure.", r: { L: "Je le signale à son supérieur, la désertion affaiblit tout le groupe.", N: "Je l'aide à se cacher mais je lui demande de quitter la région.", C: "Je l'encourage, personne ne devrait être forcé de mourir pour un seigneur." }},
        { q: "Pour vous, un bon gouvernement est défini par...", r: { L: "La stricte application des lois et une hiérarchie claire.", N: "Un équilibre entre les droits du peuple et l'autorité.", C: "Le moins de lois possibles pour laisser les gens libres." }},
        { q: "Vous gagnez un tournoi en trichant sans que personne ne s'en aperçoive.", r: { L: "Je me dénonce par respect pour le code de la chevalerie.", N: "Je garde le prix mais je ne recommencerai plus.", C: "Je savoure ma victoire, la ruse fait partie du talent." }},
        { q: "Un mystérieux étranger vous propose de renverser un roi tyrannique par un coup d'État.", r: { L: "Je refuse, on ne change pas l'ordre établi par la violence.", N: "J'attends de voir qui le remplacera avant de décider.", C: "J'accepte avec joie, les tyrans méritent le chaos." }},
        { q: "Le code d'honneur de votre famille exige une vengeance qui briserait la paix locale.", r: { L: "Je respecte le code familial, c'est ma loi suprême.", N: "Je cherche une compensation financière pour éviter le sang.", C: "Je laisse tomber la vengeance, les vieilles traditions sont inutiles." }},
        { q: "Un garde vous demande un pot-de-vin pour entrer dans la ville de nuit.", r: { L: "Je refuse et je signale son comportement à son capitaine.", N: "Je discute le prix pour ne pas trop perdre d'or.", C: "Je paie sans réfléchir, c'est ainsi que le monde fonctionne." }},
        { q: "On vous demande de superviser une élection au conseil du village.", r: { L: "Je vérifie chaque bulletin avec une rigueur absolue.", N: "Je m'assure juste que le gagnant est quelqu'un de raisonnable.", C: "Je laisse faire, le peuple choisira bien qui il veut de toute façon." }},
        { q: "Quelle est votre opinion sur les mercenaires ?", r: { L: "Des êtres peu fiables car ils n'ont pas de serment fixe.", N: "Des outils utiles selon les besoins du moment.", C: "Les plus honnêtes, car ils ne servent que leur propre liberté." }},
        { q: "Un contrat que vous avez signé devient soudainement très désavantageux pour vous.", r: { L: "Je l'honore jusqu'au bout, ma signature est mon honneur.", N: "Je tente de renégocier les termes du contrat.", C: "Je l'ignore, un contrat n'est qu'un bout de papier." }},
        { q: "Votre apprenti veut innover une technique interdite par la Guilde.", r: { L: "Je le dénonce, les règles de la Guilde assurent la qualité.", N: "Je le laisse faire tant qu'il reste discret.", C: "Je l'encourage à briser tous les vieux dogmes." }},
        { q: "Un noble commet un crime mais la loi ne peut pas le toucher à cause de son rang.", r: { L: "C'est injuste, mais changer le système causerait plus de mal.", N: "Je cherche un moyen de le discréditer socialement.", C: "Je rends la justice moi-même dans une ruelle sombre." }},
        { q: "Dans une taverne, une bagarre éclate à cause d'une insulte envers le Roi.", r: { L: "J'interviens pour défendre l'honneur de la couronne.", N: "Je finis mon verre en regardant qui va gagner.", C: "Je rejoins la bagarre juste pour le plaisir du désordre." }},
        { q: "Une prophétie dit que vous détruirez le royaume. Que faites-vous ?", r: { L: "Je m'exile ou je m'emprisonne pour protéger l'ordre.", N: "Je vis ma vie normalement en ignorant les superstitions.", C: "Je m'amuse de voir les autorités paniquer pour si peu." }},
        { q: "Vous découvrez une île qui n'appartient à aucun royaume.", r: { L: "J'y installe une colonie avec des lois strictes.", N: "J'y crée un comptoir commercial neutre.", C: "J'en fais un refuge pour les pirates et les esprits libres." }},
        { q: "Un enfant vole une pomme sur un étal. Le marchand demande justice.", r: { L: "L'enfant doit travailler pour rembourser, la règle est la règle.", N: "Je paie la pomme pour clore l'incident.", C: "Je détourne l'attention du marchand pour que l'enfant s'échappe." }},
        { q: "On vous propose un titre de noblesse si vous trahissez votre guilde.", r: { L: "Je refuse, la loyauté envers mon groupe est absolue.", N: "J'analyse quel camp sera le plus puissant demain.", C: "Je prends le titre et je verrai bien qui je trahirai ensuite." }},
        { q: "Le chaos règne dans la forêt voisine à cause de bandits.", r: { L: "Il faut lever une milice et patrouiller sans relâche.", N: "Il faut payer les bandits pour qu'ils aillent ailleurs.", C: "La forêt est plus intéressante quand elle est sauvage." }},
        { q: "Une ancienne relique de votre culte exige un rituel complexe chaque jour.", r: { L: "Je le fais sans faute, la discipline est spirituelle.", N: "Je le fais quand j'ai le temps.", C: "Je ne laisse pas un objet dicter mon emploi du temps." }},
        { q: "On vous accuse à tort d'un crime. Le procès approche.", r: { L: "Je fais confiance au système pour prouver mon innocence.", N: "Je cherche des alliés puissants pour influencer le juge.", C: "Je m'évade avant le procès, la justice est une farce." }},
        { q: "Un messager est intercepté avec des plans ennemis. Vous n'avez pas l'autorité de les lire.", r: { L: "Je livre le message scellé à mon commandant.", N: "Je regarde juste assez pour savoir si c'est urgent.", C: "Je lis tout et je décide si je vends l'info ou non." }},
        { q: "Votre monture est fatiguée mais vous devez livrer un rapport à temps.", r: { L: "Je pousse la bête, la mission prime sur tout.", N: "Je cherche une autre monture dans le prochain village.", C: "J'arrive en retard, ma monture n'est pas une machine." }},
        { q: "Le mariage arrangé d'un ami est crucial pour la paix du comté.", r: { L: "Il doit se marier, le devoir envers l'État passe avant les sentiments.", N: "Il devrait essayer de s'attacher à sa promise.", C: "Il doit s'enfuir avec son véritable amour." }},
        { q: "Un puits magique offre un savoir immense mais rend fou.", r: { L: "Il doit être scellé et gardé par l'Ordre.", N: "Il doit être étudié avec prudence par des experts.", C: "Il doit rester ouvert pour ceux qui osent tenter leur chance." }},
        { q: "Vous trouvez un trésor dans un temple abandonné.", r: { L: "Je le signale au clergé actuel de cette religion.", N: "Je prends une part pour mes frais et je laisse le reste.", C: "Je prends tout, les dieux n'ont plus besoin d'or." }},
        { q: "Quelle est votre attitude face à la mode vestimentaire ?", r: { L: "Je porte les habits de mon rang avec fierté.", N: "Je porte ce qui est pratique et discret.", C: "Je porte des couleurs vives ou étranges pour me démarquer." }},
        { q: "Un oracle vous donne la date de votre mort.", r: { L: "J'organise ma succession et mes funérailles dès maintenant.", N: "Je continue ma vie en essayant d'être prudent.", C: "Je fais les choses les plus folles avant que l'heure n'arrive." }},
        { q: "Un pont est payant mais vous êtes un chevalier.", r: { L: "Je paie, les règles s'appliquent aussi aux puissants.", N: "Je demande une remise de courtoisie.", C: "Je passe en force, mon épée est mon laissez-passer." }},
        { q: "Un village refuse de suivre une loi royale obsolète.", r: { L: "La loi doit être appliquée jusqu'à ce qu'elle soit changée officiellement.", N: "Il faut trouver un compromis local.", C: "Le village a raison de décider pour lui-même." }},
        { q: "Un mage puissant veut effacer la mémoire de tous les criminels pour les réinsérer.", r: { L: "C'est une violation de l'ordre naturel et de la punition méritée.", N: "Une idée intéressante à tester à petite échelle.", C: "C'est une horreur, l'esprit doit rester libre, même mauvais." }},
        { q: "On vous demande de brûler des livres jugés dangereux.", r: { L: "Je le fais, certaines idées peuvent détruire la société.", N: "Je sauve les plus beaux exemplaires pour ma collection.", C: "Je cache les livres et j'organise une lecture publique." }},
        { q: "Un noble vous insulte devant tout le monde.", r: { L: "Je demande réparation selon le code de duel légal.", N: "Je l'ignore, sa bêtise ne m'atteint pas.", C: "Je lui jette mon verre au visage immédiatement." }},
        { q: "Une guilde de voleurs protège votre quartier mieux que la garde.", r: { L: "C'est inadmissible, seule la garde officielle est légitime.", N: "Tant que la sécurité est là, je ne pose pas de questions.", C: "C'est parfait, l'autogestion est toujours meilleure." }},
        { q: "Le chef de votre groupe est incompétent mais légitime.", r: { L: "Je le sers du mieux possible pour maintenir l'unité.", N: "Je suggère des idées discrètement pour limiter la casse.", C: "Je provoque une mutinerie pour prendre sa place." }},
        { q: "On vous confie un secret qui pourrait détruire une famille noble.", r: { L: "Je le garde, la stabilité sociale est importante.", N: "Je l'utilise comme levier diplomatique si besoin.", C: "Je le révèle, la vérité doit éclater quel que soit le prix." }},
        { q: "Un temple interdit l'entrée aux non-croyants.", r: { L: "C'est leur droit sacré, je respecte leurs limites.", N: "Je tente d'entrer en me déguisant par curiosité.", C: "Je manifeste devant l'entrée contre cette exclusion." }},
        { q: "Un alchimiste a créé une potion qui rend tout le monde égal en force.", r: { L: "C'est un poison pour l'ordre social établi.", N: "Une découverte qui mérite d'être vendue cher.", C: "Le début d'une ère de liberté totale sans maîtres." }},
        { q: "Vous devez choisir un blason pour votre nouvelle maison.", r: { L: "Des lignes droites, des symboles de justice et de devoir.", N: "Un animal calme et une devise pragmatique.", C: "Des motifs abstraits et des couleurs provocantes." }},
        { q: "Un prisonnier de guerre demande à voir un prêtre.", r: { L: "Je l'autorise, c'est le droit des prisonniers selon le code.", N: "Seulement s'il me donne des informations en échange.", C: "Je le laisse s'échapper pendant que le prêtre arrive." }},
        { q: "Un marchand vend des produits de mauvaise qualité.", r: { L: "Je le dénonce aux inspecteurs du marché.", N: "Je ne lui achète plus rien et je préviens mes amis.", C: "Je saccage son étal pour prévenir les autres clients." }},
        { q: "Vous trouvez une faille dans la sécurité du château du Roi.", r: { L: "Je préviens le capitaine de la garde immédiatement.", N: "Je la note pour m'en servir en cas de fuite nécessaire.", C: "Je l'utilise pour faire des farces aux gardes la nuit." }},
        { q: "Une fête religieuse exige de ne pas travailler, mais votre champ va mourir.", r: { L: "Je prie et je respecte le repos, le destin fera le reste.", N: "Je travaille de nuit pour ne pas être vu.", C: "Je travaille en plein jour, ma survie prime sur les rites." }},
        { q: "Un dragon demande un tribut annuel pour ne pas brûler la ville.", r: { L: "On paie, c'est le contrat qui assure la survie.", N: "On paie tout en engageant des tueurs de dragons en secret.", C: "On refuse et on lance une attaque désespérée tout de suite." }},
        { q: "Votre épée magique a une personnalité très autoritaire.", r: { L: "J'aime ses conseils, elle m'aide à rester droit.", N: "Je l'écoute seulement quand elle a raison.", C: "Je cherche un moyen de faire taire sa voix agaçante." }},
        { q: "Une île lointaine pratique des coutumes que vous trouvez barbares.", r: { L: "Il faut leur envoyer des missionnaires pour leur apprendre la Loi.", N: "C'est leur culture, je me contente de faire du commerce.", C: "Je m'installe chez eux pour apprendre une autre façon de vivre." }},
        { q: "Un enfant prodige veut quitter son apprentissage de forgeron pour devenir barde.", r: { L: "Il doit rester, il a un engagement envers son maître.", N: "Il devrait faire les deux à mi-temps.", C: "Il doit suivre sa passion immédiatement." }},
        { q: "Vous avez la preuve que le Grand Prêtre est un imposteur.", r: { L: "Je le dis au Conseil des Sages pour une transition ordonnée.", N: "Je le fais chanter pour obtenir des faveurs pour le peuple.", C: "Je crie la vérité sur la place publique en plein sermon." }},
        { q: "Le mur de votre voisin empiète de dix centimètres sur votre terrain.", r: { L: "Je fais appel à un géomètre officiel pour trancher.", N: "Je lui demande une petite compensation financière.", C: "Je démolit la partie qui dépasse pendant la nuit." }},
        { q: "On vous propose l'immortalité si vous servez un dieu de l'ordre pour l'éternité.", r: { L: "J'accepte, une existence dévouée à une structure me rassure.", N: "Je demande si j'ai des vacances.", C: "Je refuse, l'éternité sans liberté est une prison." }}
    ],

    // ── AXE MORALE : Bon vs Mauvais ─────────────────────────────
    "morale": [
        { q: "Un villageois est accusé de vol pour nourrir sa famille. La sentence est la main coupée.",
          r: { B: "Je paie sa dette pour qu'il soit libéré.", N: "Je demande une remise de peine en échange de travaux.", M: "La loi est la loi — je laisse la sentence s'exécuter." }},
        { q: "Vous découvrez une fontaine de jouvence qui ne peut soigner qu'une seule personne.",
          r: { B: "Je l'offre au plus vieux sage du royaume.", N: "Je la vends au plus offrant pour financer mon équipement.", M: "Je bois l'eau moi-même pour devenir immortel." }},
        { q: "Un dragon mourant vous supplie de protéger son dernier œuf.",
          r: { B: "Je jure de le protéger au péril de ma vie.", N: "Je le confie à un monastère en échange d'une faveur.", M: "Je brise l'œuf pour récupérer ses composants magiques précieux." }},
        { q: "Face à un ennemi désarmé qui demande grâce, vous...",
          r: { B: "Je l'épargne et lui offre une chance de rédemption.", N: "Je l'emprisonne pour qu'il ne nuise plus.", M: "Je l'achève pour être sûr qu'il ne revienne jamais." }},
        { q: "Un sorcier vous propose un sort puissant en échange de dix ans de vie d'un inconnu.",
          r: { B: "Je refuse catégoriquement — personne ne mérite ce sacrifice.", N: "Je refuse mais cherche un autre marché avec le sorcier.", M: "J'accepte — un inconnu pour un grand pouvoir, c'est raisonnable." }},
        { q: "Vous avez la possibilité d'enrichir votre village en empoisonnant la source d'eau d'un village rival.",
          r: { B: "Jamais — je trouverai une autre voie pour enrichir les miens.", N: "Je cherche une façon de les affaiblir sans mettre des vies en danger.", M: "Je le fais — la survie des miens prime sur tout." }},
        { q: "Un mendiant vous tend la main devant la taverne. Vous...",
          r: { B: "Lui donnez vos dernières pièces et l'invitez à dîner.", N: "Lui donnez une pièce — c'est déjà quelque chose.", M: "Passez votre chemin — la charité entretient la faiblesse." }},
        { q: "Vous pouvez sauver 10 personnes inconnues ou une personne que vous aimez. Vous...",
          r: { B: "Sauvez les 10 inconnus — le bien du plus grand nombre prime.", N: "Cherchez désespérément un moyen de sauver tout le monde.", M: "Sauvez la personne que vous aimez sans hésiter." }},
        { q: "Un négociant vous vend sciemment une monture malade. Vous le découvrez après. Vous...",
          r: { B: "Lui pardonnez après avoir exigé réparation pour la monture.", N: "Réclamez un remboursement complet et le signalez aux autorités.", M: "Revenez cette nuit vider sa caisse — il l'a bien mérité." }},
        { q: "Vous trouvez un orphelin sur la route en plein hiver. Vous...",
          r: { B: "L'emmenez avec vous et subvenez à ses besoins.", N: "L'amenez au prochain village avec une pièce pour son gîte.", M: "Continuez votre route — le monde est dur pour tout le monde." }},
        { q: "Un ami vous demande de mentir pour le sortir d'un mauvais pas. Vous...",
          r: { B: "Refusez le mensonge mais l'aidez à trouver une solution honnête.", N: "Mentez une fois si les conséquences pour autrui sont mineures.", M: "Mentez sans hésiter — la loyauté envers les siens avant tout." }},
        { q: "Vous découvrez un secret compromettant sur un rival. Vous...",
          r: { B: "Le gardez pour vous — utiliser ce secret serait indigne.", N: "Le conservez comme assurance mais ne l'utilisez pas activement.", M: "L'utilisez immédiatement pour éliminer la concurrence." }},
        { q: "Une guérisseuse peut soigner tous les enfants malades du village ou un seigneur puissant. Vous décidez...",
          r: { B: "Les enfants, sans hésitation — le seigneur peut attendre.", N: "Le seigneur d'abord s'il finance les soins des enfants ensuite.", M: "Le seigneur — son influence nous protégera à long terme." }},
        { q: "Votre victoire passe par la destruction d'un village neutre. Vous...",
          r: { B: "Refusez — aucune victoire ne justifie d'innocents massacrés.", N: "Cherchez une stratégie alternative même plus coûteuse.", M: "Donnez l'ordre — la guerre a ses règles cruelles." }},
        { q: "Un espion capturé possède des informations vitales. La torture est proposée. Vous...",
          r: { B: "Refusez fermement — il existe des méthodes plus humaines.", N: "Autorisez une pression psychologique mais pas physique.", M: "Autorisez tout — les informations sauvent plus de vies qu'elles n'en détruisent." }},
        { q: "Vous pouvez rester anonyme après avoir fait quelque chose de bien. Vous...",
          r: { B: "Restez dans l'ombre — le bien n'a pas besoin de témoin.", N: "Restez discret mais ne niez pas si quelqu'un vous retrouve.", M: "Revendiquez publiquement pour en tirer profit." }},
        { q: "Un mage offre de maudire votre ennemi en échange de votre première victoire militaire. Vous...",
          r: { B: "Refusez — la magie noire ne m'appartient pas.", N: "Réfléchissez longuement selon la gravité de la menace.", M: "Acceptez — une malédiction économise des batailles." }},
        { q: "Vous héritez d'une fortune bâtie sur l'esclavage. Vous...",
          r: { B: "La redistribuez intégralement aux descendants des victimes.", N: "En donnez une partie significative et bâtissez quelque chose de juste.", M: "La gardez — les erreurs du passé ne sont pas les vôtres." }},
        { q: "Un enfant vous offre sa seule pièce d'or pour que vous le vengez. Vous...",
          r: { B: "Refusez l'argent mais l'aidez quand même.", N: "Acceptez la mission mais lui rendrez l'argent à la fin.", M: "Prenez la pièce et évaluez si la mission vous profite vraiment." }},
        { q: "Une épidémie touche une région pauvre et une région riche. Vous avez un seul remède. Vous...",
          r: { B: "L'envoyez dans la région la plus touchée, peu importe le rang.", N: "Divisez le remède pour aider les deux régions partiellement.", M: "L'envoyez là où vous avez le plus à gagner politiquement." }},
        { q: "Votre victoire dépend d'un allié que vous savez innocent d'une accusation. Vous...",
          r: { B: "Prouvez son innocence même si ça compromet votre campagne.", N: "Travaillez en parallèle pour le disculper discrètement.", M: "Laissez l'accusation courir jusqu'à la victoire — le temps arrangera tout." }},
        { q: "Vous pouvez gagner une guerre en ruinant l'économie ennemie, affamant civils compris. Vous...",
          r: { B: "Refusez — on ne gagne pas une guerre sur des cadavres d'enfants.", N: "Cherchez une stratégie économique qui épargne les civils.", M: "Procédez — une faim temporaire vaut mieux qu'une guerre éternelle." }},
        { q: "Un condamné à mort vous révèle où se cache un dangereux criminel. En échange il demande la liberté. Vous...",
          r: { B: "Promettez et tenez parole, puis travaillez à sa réhabilitation.", N: "Promettez la liberté après confirmation des infos.", M: "Prenez l'information et laissez la sentence s'accomplir." }},
        { q: "Vous pouvez sauver votre honneur en sacrifiant la réputation d'un innocent. Vous...",
          r: { B: "Jamais — mon honneur n'a de valeur que s'il est réel.", N: "Cherchez une issue qui ne nuise à personne.", M: "Sacrifiez l'innocent — la survie de ma réputation est en jeu." }},
        { q: "Un vieil ennemi est tombé dans la misère. Vous le croisez par hasard. Vous...",
          r: { B: "Lui offrez de l'aide sans conditions — les vieilles rancœurs s'effacent.", N: "Passez votre chemin sans l'aider ni lui nuire.", M: "Profitez de l'occasion pour achever sa ruine." }},
        { q: "Une rumeur fausse sur vous se répand. La corriger nuirait à un ami. Vous...",
          r: { B: "Corrigez la rumeur quand même — la vérité vaut ce sacrifice.", N: "Parlez en privé à votre ami pour trouver une solution ensemble.", M: "Laissez courir la rumeur — si ça vous arrange, pourquoi pas." }},
        { q: "On vous offre une récompense pour avoir accompli votre devoir. Vous...",
          r: { B: "Refusez — le devoir ne se monnaie pas.", N: "Acceptez si la récompense est raisonnable et méritée.", M: "Négociez pour obtenir le maximum avant de conclure." }},
        { q: "Un sorcier peut vous rendre invincible en échange des souvenirs heureux d'un enfant. Vous...",
          r: { B: "Refusez avec indignation — jamais au détriment d'un enfant.", N: "Cherchez une alternative moins cruelle avec le sorcier.", M: "Acceptez — un enfant oubliera, vous avez une mission à accomplir." }},
        { q: "Vous pouvez dénoncer un ami pour un crime mineur qu'il a commis. Vous...",
          r: { B: "L'encouragez à se dénoncer lui-même et l'accompagnez.", N: "Négociez avec lui pour qu'il répare le tort sans se dénoncer.", M: "Utilisez cette information comme levier si vous en avez besoin un jour." }},
        { q: "Un ennemi blessé demande de l'eau sur le champ de bataille. Vous...",
          r: { B: "Lui tendez votre gourde sans hésiter.", N: "Lui donnez de l'eau mais restez sur vos gardes.", M: "Passez votre chemin — l'ennemi reste l'ennemi." }},
        { q: "Une sorcière peut sauver votre village en sacrifiant un criminel condamné. Vous...",
          r: { B: "Refusez — même un criminel a droit à sa vie.", N: "Cherchez une alternative avant d'accepter.", M: "Acceptez sans hésiter — il méritait pire de toute façon." }},
        { q: "Vous surprenez un serviteur qui vole de la nourriture pour sa famille affamée. Vous...",
          r: { B: "Ne dites rien et augmentez discrètement son salaire.", N: "Parlez-lui en privé et trouvez une solution juste.", M: "Le renvoyez immédiatement — le vol reste le vol." }},
        { q: "On vous propose de tester une arme nouvelle sur des condamnés à mort. Vous...",
          r: { B: "Refusez catégoriquement — personne n'est un cobaye.", N: "Refusez mais proposez des tests sur des animaux ou des cibles inanimées.", M: "Acceptez — ils sont condamnés de toute façon, autant que ça serve." }},
        { q: "Votre victoire finale est à portée mais votre ennemi vous révèle qu'il a une famille. Vous...",
          r: { B: "Offrez la paix — une famille change tout à l'équation.", N: "Concluez la paix si les conditions sont acceptables.", M: "Continuez — la sentimentalité n'a pas sa place sur un champ de bataille." }},
        { q: "Vous pouvez récupérer une relique sacrée en pillant un temple ennemi. Vous...",
          r: { B: "Négociez son rachat — les lieux de culte sont sacrés.", N: "La prenez discrètement en laissant une compensation.", M: "La prenez de force — la victoire légitime les trophées." }},
        { q: "Un mendiant affirme être un ancien roi déchu. Vous...",
          r: { B: "L'aidez de toute façon — sa parole importe peu, sa détresse oui.", N: "Vérifiez son histoire avant de décider quoi faire.", M: "Passez — si c'est vrai, il a eu sa chance de régner." }},
        { q: "Un alchimiste peut doubler vos récoltes en polluant une rivière en aval. Vous...",
          r: { B: "Refusez — les gens en aval ont autant droit à l'eau pure.", N: "Cherchez avec l'alchimiste une méthode moins polluante.", M: "Acceptez — votre peuple passe avant les inconnus en aval." }},
        { q: "Vous gagnez une bataille grâce à une ruse qui humilie publiquement l'ennemi. Vous...",
          r: { B: "Offrez à l'ennemi une sortie digne après la victoire.", N: "Profitez de la victoire sans en rajouter.", M: "Exploitez l'humiliation au maximum pour briser leur moral définitivement." }},
        { q: "On vous demande de témoigner contre un ami dont vous savez qu'il est coupable. Vous...",
          r: { B: "Témoignez honnêtement — la vérité lui rendra service à long terme.", N: "Témoignez avec nuance pour atténuer sa peine.", M: "Refusez de témoigner — la loyauté prime sur la justice." }},
        { q: "Une prophétie dit que vous pouvez sauver le monde en sacrifiant votre propre bonheur. Vous...",
          r: { B: "Acceptez sans hésiter — le monde vaut mon bonheur.", N: "Cherchez si la prophétie a une interprétation moins radicale.", M: "Cherchez quelqu'un d'autre pour faire ce sacrifice." }},
        { q: "Vous découvrez que votre mentor bien-aimé a commis des crimes dans sa jeunesse. Vous...",
          r: { B: "L'encouragez à se confesser et l'aidez à réparer ses torts.", N: "Lui en parlez en privé et laissez-le choisir sa voie.", M: "Gardez cette information pour vous — ou pour plus tard." }},
        { q: "Un enfant pauvre a du talent mais pas de ressources. Vous...",
          r: { B: "Financez sa formation vous-même et sans condition.", N: "L'aidez à trouver un mécène ou une bourse.", M: "C'est à lui de trouver comment s'en sortir — le talent ne suffit pas." }},
        { q: "Vous pouvez trahir un secret d'État pour sauver des vies innocentes. Vous...",
          r: { B: "Révélez le secret — des vies valent plus que des secrets politiques.", N: "Cherchez une façon de sauver ces vies sans révéler le secret.", M: "Gardez le secret — votre position importe plus que ces vies." }},
        { q: "Un artisan produit des œuvres magnifiques mais exploite ses apprentis. Vous...",
          r: { B: "Dénoncez ses pratiques même si ses œuvres vous manqueront.", N: "L'avertissez en privé et lui donnez une chance de changer.", M: "Continuez à acheter ses œuvres — ce qui se passe chez lui ne vous regarde pas." }},
        { q: "Vous pouvez choisir entre une victoire glorieuse avec des pertes ou une victoire humble sans victimes. Vous...",
          r: { B: "La victoire humble sans victimes, sans même hésiter.", N: "Évaluez les deux options selon le contexte stratégique.", M: "La victoire glorieuse — les grandes choses demandent de grands sacrifices." }},
        { q: "Un noble vous offre une fortune pour fermer les yeux sur ses abus envers ses serfs. Vous...",
          r: { B: "Refusez et dénoncez ses abus immédiatement.", N: "Refusez l'argent et l'avertissez sévèrement.", M: "Prenez l'argent — les serfs ont toujours été mal traités de toute façon." }},
        { q: "Quelle est selon vous la plus grande vertu ?",
          r: { B: "La compassion — souffrir avec autrui et agir pour le soulager.", N: "La sagesse — peser chaque acte pour le plus grand bien.", M: "La force — seuls les forts peuvent vraiment protéger les leurs." }},
        { q: "Un paysan vous offre sa seule vache pour payer votre protection. Vous...",
          r: { B: "Refusez la vache et le protégez gratuitement.", N: "Acceptez la moitié de ce qu'il propose.", M: "Prenez la vache — un service mérite compensation." }},
        { q: "On vous propose d'assassiner un tyran en échange de paix pour votre peuple. Vous...",
          r: { B: "Cherchez une autre voie — tuer est toujours le dernier recours.", N: "Pesez longuement les conséquences avant de décider.", M: "Acceptez sans états d'âme — un tyran de moins, c'est toujours mieux." }},
        { q: "Vous pouvez sauver un village en brûlant la forêt sacrée qui le protégeait depuis des siècles. Vous...",
          r: { B: "Cherchez une alternative coûteuse mais respectueuse de l'héritage.", N: "Brûlez la forêt en promettant de la replanter sur plusieurs générations.", M: "Brûlez sans hésiter — les vivants d'aujourd'hui comptent plus que les symboles." }},
        { q: "Un mendiant vous demande une pièce pour manger.", r: { B: "Je lui donne assez pour plusieurs repas.", N: "Je lui donne une petite pièce de cuivre.", M: "Je lui dis de trouver un travail et je l'ignore." }},
        { q: "Votre groupe capture un espion ennemi qui a des enfants.", r: { B: "Je demande qu'on le traite avec humanité et qu'on l'épargne.", N: "Je propose de l'échanger contre un de nos prisonniers.", M: "Je suggère de l'exécuter pour envoyer un message clair." }},
        { q: "Vous trouvez un anneau de pouvoir qui permet d'aider les gens ou de dominer.", r: { B: "Je l'utilise pour soigner les malades anonymement.", N: "Je le garde comme assurance pour ma propre sécurité.", M: "Je l'utilise pour devenir le nouveau seigneur de la région." }},
        { q: "Un incendie se déclare dans l'écurie d'un homme que vous détestez.", r: { B: "Je me précipite pour sortir les chevaux des flammes.", N: "J'appelle les secours mais je ne prends pas de risques.", M: "Je regarde le spectacle en souriant discrètement." }},
        { q: "Vous apprenez qu'un remède miracle est fabriqué à partir d'une plante rare et sacrée.", r: { B: "Je protège la plante pour qu'elle ne disparaisse jamais.", N: "J'en prends juste assez pour soigner ma famille.", M: "Je rase la forêt pour vendre le remède au prix fort." }},
        { q: "Un inconnu se noie dans une rivière tumultueuse.", r: { B: "Je plonge immédiatement malgré le danger pour ma vie.", N: "Je lui lance une corde en espérant qu'il l'attrape.", M: "Je regarde s'il a une bourse qui pourrait flotter après sa mort." }},
        { q: "Votre roi vous ordonne de raser un village de paysans innocents.", r: { B: "Je refuse et je me rebelle contre ce tyran.", N: "J'essaie de convaincre le roi de changer d'avis sans succès.", M: "J'exécute les ordres, après tout, je ne suis qu'un soldat." }},
        { q: "On vous propose de sacrifier un peu de votre force pour sauver un étranger.", r: { B: "J'accepte le sacrifice sans hésiter.", N: "Je demande qui est cet étranger avant de décider.", M: "Je refuse, ma force est ma seule protection." }},
        { q: "Vous découvrez que le trésor que vous venez de trouver appartient à une veuve.", r: { B: "Je lui rends chaque pièce d'or.", N: "Je lui en rends la moitié en guise de récompense.", M: "Je garde tout, elle ne sait même pas qu'il était là." }},
        { q: "Que pensez-vous du pardon ?", r: { B: "C'est la plus grande des vertus humaines.", N: "C'est une option si l'autre s'est vraiment repenti.", M: "C'est une faiblesse qui encourage les autres à recommencer." }},
        { q: "Une sorcière vous offre de maudire votre pire ennemi en échange d'une faveur.", r: { B: "Je refuse, la vengeance ne mène qu'à la souffrance.", N: "Je lui demande quelle est la faveur d'abord.", M: "J'accepte, je veux le voir ramper dans la boue." }},
        { q: "Un compagnon d'arme est gravement blessé et vous ralentit dans votre fuite.", r: { B: "Je le porte sur mon dos, quitte à être capturé.", N: "Je lui laisse des armes pour qu'il se défende seul.", M: "Je l'abandonne pour sauver ma propre vie." }},
        { q: "Vous avez le pouvoir de supprimer la faim dans le monde au prix de votre mémoire.", r: { B: "Je le fais, mon identité est peu de chose face à la fin du monde.", N: "J'hésite longuement et je finis par ne rien faire.", M: "Je refuse, mes souvenirs sont tout ce que je possède." }},
        { q: "Un marchand vous rend trop de monnaie par erreur.", r: { B: "Je lui signale l'erreur et je rends le surplus.", N: "Je garde le surplus mais je lui achète plus de choses.", M: "Je pars vite en me réjouissant de ma chance." }},
        { q: "Votre mission est de livrer un message qui déclenchera une guerre sanglante.", r: { B: "Je détruis le message pour préserver la paix.", N: "Je livre le message sans me poser de questions morales.", M: "Je livre le message et j'investis dans les forges d'armes." }},
        { q: "Que feriez-vous si vous étiez témoin d'une injustice flagrante envers un gobelin ?", r: { B: "Je m'interpose, chaque être mérite d'être traité équitablement.", N: "Je passe mon chemin, les gobelins ne sont pas mon problème.", M: "Je me joins à l'injustice pour m'amuser un peu." }},
        { q: "On vous propose une potion de vérité infinie. Comment l'utilisez-vous ?", r: { B: "Pour débusquer les corrompus et libérer les innocents.", N: "Pour savoir ce que mes amis pensent vraiment de moi.", M: "Pour faire chanter les nobles et obtenir du pouvoir." }},
        { q: "Un noble offre une prime pour capturer un innocent qui a vu son crime.", r: { B: "Je protège l'innocent et je dénonce le noble.", N: "Je ne me mêle pas de cette affaire dangereuse.", M: "Je capture l'innocent pour toucher la prime." }},
        { q: "Un dragon propose de protéger votre ville en échange d'un enfant par an.", r: { B: "Je préfère que la ville brûle plutôt que de sacrifier un enfant.", N: "Je cherche une solution alternative magique.", M: "J'organise une loterie pour choisir l'enfant à sacrifier." }},
        { q: "Votre famille est menacée. Pour les sauver, vous devez tuer un saint homme.", r: { B: "Je cherche une autre issue, je ne peux pas commettre ce sacrilège.", N: "Je le fais la mort dans l'âme pour protéger les miens.", M: "Je le fais sans hésiter, ma famille avant tout le reste." }},
        { q: "Vous trouvez un champignon qui peut nourrir un village pendant un mois.", r: { B: "Je le partage gratuitement avec tous les habitants.", N: "Je le vends à un prix raisonnable au maire.", M: "Je le garde pour mes propres provisions personnelles." }},
        { q: "Un chevalier noir vous défie. Si vous gagnez, il libère ses esclaves.", r: { B: "J'accepte le défi au péril de ma vie.", N: "Je demande des alliés pour être sûr de gagner.", M: "Je lui propose de devenir son allié contre une part des esclaves." }},
        { q: "Un vieux sage vous demande de l'aider à traverser une montagne.", r: { B: "Je l'accompagne et je porte ses bagages.", N: "Je lui donne une carte et quelques conseils.", M: "Je lui demande de l'or avant de faire un pas." }},
        { q: "Que ressentez-vous quand vous voyez quelqu'un réussir par la triche ?", r: { B: "De la tristesse pour son manque d'intégrité.", N: "De l'indifférence tant que ça ne me nuit pas.", M: "De l'admiration pour son ingéniosité." }},
        { q: "On vous confie la garde d'un orphelinat pendant une nuit d'attaque.", r: { B: "Je me tiens devant la porte et je me bats jusqu'à la mort.", N: "Je cache les enfants et je me cache avec eux.", M: "Je m'enfuis par la porte de derrière dès le premier cri." }},
        { q: "Vous avez une pomme et vous voyez deux personnes affamées.", r: { B: "Je leur donne la pomme et je ne mange rien.", N: "Je la coupe en trois parts égales.", M: "Je la mange vite avant qu'ils ne me la demandent." }},
        { q: "Un criminel repenti vous demande de l'aide pour se racheter.", r: { B: "Je lui donne une chance et je l'accompagne dans ses efforts.", N: "Je reste méfiant mais je lui indique une tâche utile.", M: "Je le dénonce pour son passé, il ne changera jamais." }},
        { q: "Vous trouvez une arme légendaire mais elle est maudite et blesse son utilisateur.", r: { B: "Je l'enterre pour que personne ne soit blessé.", N: "Je la vends à un marchand d'antiquités.", M: "Je l'offre à un ennemi en guise de cadeau de paix." }},
        { q: "Quelle est votre définition de la bravoure ?", r: { B: "Se sacrifier pour une cause plus grande que soi.", N: "Faire face au danger quand c'est nécessaire.", M: "Ecraser ses peurs pour dominer les autres." }},
        { q: "On vous propose de vivre dans un palais si vous oubliez votre passé de paysan.", r: { B: "Je refuse, mes racines font de moi ce que je suis.", N: "J'accepte, le confort vaut bien un peu d'oubli.", M: "J'accepte et je fais raser mon ancien village pour effacer les traces." }},
        { q: "Vous voyez un boucher maltraiter son chien.", r: { B: "J'interviens et je sauve l'animal.", N: "Je lui fais une remarque désapprobatrice.", M: "Je ne fais rien, c'est son animal après tout." }},
        { q: "Un génie vous offre trois vœux. Quel est le premier ?", r: { B: "La fin de la pauvreté dans le royaume.", N: "Une armure enchantée indestructible.", M: "La mort de tous ceux qui se sont moqués de moi." }},
        { q: "Un espion vous propose des infos sur une attaque imminente contre un village rival.", r: { B: "Je préviens le village rival pour sauver des vies.", N: "Je ne fais rien, ce ne sont pas mes oignons.", M: "Je rejoins l'attaque pour piller les restes du village." }},
        { q: "Que faites-vous d'un ennemi capturé qui a tué votre frère ?", r: { B: "Je le livre à la justice pour un procès équitable.", N: "Je l'enferme dans un cachot sombre pour le reste de sa vie.", M: "Je l'exécute lentement pour savourer ma vengeance." }},
        { q: "Une potion peut soigner la peste mais elle coûte la vie d'un animal rare.", r: { B: "Je l'utilise pour sauver les humains mourants.", N: "J'hésite sur la valeur de la vie animale.", M: "Je ne l'utilise que si on me paie très cher." }},
        { q: "On vous propose de diriger une guilde d'assassins.", r: { B: "Je refuse et je tente de démanteler la guilde.", N: "J'accepte pour transformer la guilde en groupe d'espions.", M: "J'accepte et je commence à éliminer mes rivaux." }},
        { q: "Vous trouvez un carnet intime d'une personne célèbre.", r: { B: "Je le lui rends sans le lire.", N: "Je le lis par curiosité puis je le brûle.", M: "Je le vends aux colporteurs de rumeurs." }},
        { q: "Un paysan vous offre son dernier pain pour vous remercier d'un service.", r: { B: "Je refuse poliment car il en a plus besoin que moi.", N: "Je prends le pain mais je lui donne quelques pièces.", M: "Je prends le pain et je me plains qu'il soit rassis." }},
        { q: "Vous avez le choix entre sauver 100 inconnus ou 1 ami très proche.", r: { B: "Je sauve les 100 inconnus, la vie est une question de nombre.", N: "Je sauve mon ami, les inconnus ne comptent pas pour moi.", M: "Je sauve celui qui pourra me récompenser le mieux." }},
        { q: "Une sirène vous propose de vivre sous l'eau dans le luxe mais vous ne reverrez plus la terre.", r: { B: "Je refuse, j'ai encore trop de gens à aider ici.", N: "J'accepte, la vie sur terre est trop difficile.", M: "J'accepte et j'aide la sirène à couler les navires marchands." }},
        { q: "Un enfant vous défie en duel avec une épée en bois.", r: { B: "Je joue le jeu et je le laisse gagner avec panache.", N: "Je l'ignore, je n'ai pas de temps à perdre.", M: "Je lui montre la supériorité d'une vraie lame." }},
        { q: "On vous demande de tester un nouveau vaccin sur des prisonniers.", r: { B: "Je refuse, c'est une violation de la dignité humaine.", N: "Je le fais si les prisonniers sont des meurtriers.", M: "Je le fais sans remords, ils sont déjà condamnés." }},
        { q: "Vous trouvez une licorne blessée. Son sang donne la force éternelle.", r: { B: "Je soigne ses blessures et je la laisse partir.", N: "Je prends juste une goutte de sang et je la soigne.", M: "Je la tue pour récolter tout son sang." }},
        { q: "Quelle est votre réaction face à un mendiant qui vous insulte ?", r: { B: "Je l'ignore et je lui souhaite de trouver la paix.", N: "Je lui demande pourquoi il est si en colère.", M: "Je lui donne un coup de pied pour lui apprendre le respect." }},
        { q: "Un esprit vous propose de voir l'avenir de vos enfants.", r: { B: "Je refuse, ils doivent forger leur propre destin.", N: "Je regarde pour pouvoir les guider un peu.", M: "Je regarde pour savoir s'ils seront dignes de mon héritage." }},
        { q: "Que faites-vous d'une arme qui peut détruire une ville entière ?", r: { B: "Je la jette au fond de l'océan le plus profond.", N: "Je la remets au Roi pour la défense du royaume.", M: "Je m'en sers comme menace pour obtenir ce que je veux." }},
        { q: "Un villageois est injustement banni. Il vous demande de l'héberger.", r: { B: "Je l'accueille et je l'aide à prouver son innocence.", N: "Je lui donne un peu de nourriture et je lui dis de partir vite.", M: "Je le livre aux autorités pour obtenir une faveur." }},
        { q: "Vous avez la chance de devenir un dieu, mais vous devez oublier l'amour.", r: { B: "Je refuse, l'amour est ce qui donne un sens à la vie.", N: "J'hésite, le pouvoir divin permet d'aider tant de gens.", M: "J'accepte, l'amour n'est qu'une distraction pour les faibles." }},
        { q: "Un barde chante une chanson insultante sur vous.", r: { B: "J'en ris et je lui offre un verre pour son talent.", N: "Je lui demande d'arrêter calmement.", M: "Je lui coupe les cordes de sa lyre... ou ses doigts." }},
        { q: "Votre dernier acte avant de mourir serait de...", r: { B: "Pardonner à tous mes ennemis.", N: "M'assurer que ma famille est à l'abri du besoin.", M: "Maudire le monde entier pour mon départ." }}
    ]
};
